export const capstone = [
    {
        title: 'INNOVATION IN IT',
        videoId: 'wPE2I0WE1hU',
        lang: 'IOT',
        ppt:require('./../assets/IOT.pptx'),
        desc: 'The Internet of Things (IoT) represents a groundbreaking innovation in the field of Information Technology, enabling the connection of everyday objects to the internet, allowing them to collect, exchange, and act on data autonomously. This technology is driving significant advancements across multiple sectors, including healthcare, agriculture, transportation, and smart cities, by enhancing efficiency, enabling real-time decision-making, and creating new opportunities for automation and data-driven insights. Recent developments in edge computing, 5G connectivity, and AI integration are further expanding the capabilities of IoT, making devices smarter and more responsive. Despite its transformative potential, IoT also presents challenges related to security, privacy, interoperability, and scalability, which must be addressed to ensure its sustainable and secure deployment. As IoT continues to evolve, it is poised to play a central role in the digital transformation of industries and society, offering profound benefits while also requiring concerted efforts to overcome its inherent risks and complexities.',
        desc1: 'Kiswahili--Mtandao wa Vitu (IoT) ni uvumbuzi wa kisasa katika uwanja wa Teknolojia ya Habari, unaowezesha uunganishaji wa vitu vya kila siku kwenye mtandao, na hivyo kuruhusu kukusanya, kubadilishana, na kuchakata data kwa njia huru. Teknolojia hii inaendesha maendeleo makubwa katika sekta nyingi kama vile afya, kilimo, usafirishaji, na miji mizuri kwa kuongeza ufanisi, kuwezesha maamuzi ya papo hapo, na kuunda fursa mpya za otomatiki na uchambuzi wa data. Maendeleo ya hivi karibuni katika hesabu za pembezoni, muunganisho wa 5G, na ujumuishaji wa AI yanapanua zaidi uwezo wa IoT, na kufanya vifaa kuwa na akili zaidi na vyenye mwitikio. Licha ya uwezo wake mkubwa wa kubadilisha hali, IoT pia ina changamoto zinazohusiana na usalama, faragha, utangamano, na upanuzi, ambazo lazima zishughulikiwe ili kuhakikisha utekelezaji wake endelevu na salama. Kadri IoT inavyoendelea, inatarajiwa kuwa na jukumu kuu katika mabadiliko ya kidijitali ya viwanda na jamii, ikitoa manufaa makubwa huku pia ikihitaji juhudi za pamoja kushinda hatari na ugumu wake wa asili.',
        desc2: "Internet mar Gik (IoT) en kare mar bedo gi kar teko manyo mar teko e kido mar Yore mag Teko manyalo kuanyo gik ma ipimo e Internet mondo gi tim nyalo medie, ywayie, kendo los adieri gi kethruok manyalo tim adiera. Kare man-gi mar telo timo paro e yo marokore goyo nyiso e mich motegno, kendo telore machiegni e ber ne nege mar yie, ywayie, kendo neno wa gi kido goyo adiera gi teko nyalo timore adier, nyaka mano telore mag adiera, neno goyo adiera kendo dhi e kinde matin. Weche manyalo mar teko mar nyasaye goyo adiera, ombulu goyo nyiso adiera kendo dhi e kinde matin kendo oting'o nyalo adiera e yo manyalo wuokore gi teko mar neno adiera. Okeyo goyo kendo e duogore gi luong adiera, nyasaye goyo, adiera, kendo dhi e kinde matin. Lelo kendo goyo wach mar teko mar neno adiera, kendo dhi e kinde matin gi wach manade gi nyalo, adiera, nyalo tim adier, nyasaye goyo adiera kendo dhi e kinde matin e nyalo matut gi weche goyo adiera e yo mag goyo adiera kendo dhi e kinde matin kendo dhi e kinde matin kendo dhi e kinde matin kendo dhi e kinde matin kendo dhi e kinde matin."
    },
    {
        title: 'ASPECT OF AFRICAN CULTURE',
        videoId: 'qRTGZXTNIlw',
        lang: 'Respect To Elders',
        ppt:require('./../assets/RESPECT TO ELDERS.pptx'),
        desc: 'Respect for elders is a fundamental aspect of African culture, deeply embedded in the traditions and social structures of various communities. This practice, which honors the wisdom, experience, and authority of older generations, plays a crucial role in maintaining cultural heritage, social stability, and intergenerational harmony. However, it also presents challenges, particularly in the context of gender inequality and resistance to change. As African societies evolve, there is a growing need to adapt this tradition to modern realities while preserving its core values. Emphasizing gender equality and leveraging technology and education are key to ensuring that the respect for elders remains relevant and meaningful in contemporary times.',
        desc1: 'Kuheshimu wazee ni sehemu muhimu ya utamaduni wa Kiafrika, ikiwa imejikita sana katika mila na miundo ya kijamii ya jamii mbalimbali. Utamaduni huu, unaoheshimu hekima, uzoefu, na mamlaka ya vizazi vya zamani, unachangia sana kuhifadhi urithi wa kitamaduni, utulivu wa kijamii, na maelewano kati ya vizazi. Hata hivyo, pia una changamoto, hasa katika muktadha wa usawa wa kijinsia na upinzani kwa mabadiliko. Kadri jamii za Kiafrika zinavyoendelea kubadilika, kuna haja ya kuendana na hali halisi za kisasa huku zikihifadhi thamani kuu za utamaduni huu. Kuzingatia usawa wa kijinsia na kutumia teknolojia na elimu ni muhimu ili kuhakikisha kuwa kuheshimu wazee kunabaki kuwa muhimu na na maana katika nyakati za sasa.',
        desc2: "Luor ni jomoke en kare mar mana winjo kaka kit mar winjo jowa Africa, kendo nene tie kod ket miyo kuom kit gi yore mag luor gi kit makare manyono. Kit man, ma luor hekima, loso, gi kare mar jomoko, nyalo rangore kare e kuonge kare mar anywol, neno goyo adiera, gi luor e kinde man-gi. Kata kamano, kit man omedo goyo, moloyo kaka chopo mar gi goyo machiegni kuom luor gi kit man kare makare. Kaka luor mag nyikwa Africa dhi nyime, to en kare gi gi medore gi wach mori luor gi ng'iyo mar goyo mar chiegni. Goyo adiera mar gi luor gi tich gi piny ni goyo manade gi luor e kinde man-gi gi gi nyalore.",
    },
    {
        title: 'Challenge in Modern Society',
        videoId: 'Fnr_Bg7jYq8',
        ppt:require('./../assets/HEALTHCARE ACCESS.pptx'),
        lang: 'Natural Remedies as Solution',
        desc: 'This video explores the challenges of medical access in modern African society, highlighting key factors such as geographical barriers, economic constraints, limited healthcare infrastructure, and lack of awareness and education. It then discusses the potential of locally available natural remedies as a complementary solution, addressing their cultural relevance, affordability, and role in preserving biodiversity and traditional knowledge. Additionally, the document examines the role of electronic access to healthcare, including telemedicine, mobile health applications, electronic health records, and online health information platforms, in improving healthcare delivery across the continent.',
        desc1: 'Video hii inachunguza changamoto za upatikanaji wa huduma za matibabu katika jamii ya kisasa ya Afrika, akiangazia mambo muhimu kama vile vikwazo vya kijiografia, matatizo ya kiuchumi, upungufu wa miundombinu ya afya, na upungufu wa ufahamu na elimu. Inaelezea pia uwezo wa dawa za asili zinazopatikana hapa nchini kama suluhisho la ziada, ikizungumzia umuhimu wake wa kitamaduni, urahisi wa kupatikana, na jukumu lake katika kuhifadhi utamaduni na maarifa ya asili. Aidha, hati hii inachunguza jukumu la upatikanaji wa elektroniki wa huduma za afya, ikijumuisha telematimu, programu za afya za simu, rekodi za afya za kidijitali, na majukwaa ya habari za afya mtandaoni, katika kuboresha utoaji wa huduma za afya katika bara hili.',
        desc2: "Warri/Wilowacho machiel ni e romo gi wach kite mi kuom achiel e geng' ma onge gi wach maywague, kata kama onego oket ne e dhano malong'o maber. Ne en jo kanyakla ma ne riwo piny chieng' kata dhi ei kanyakla ma gima ok ni e yo mar biro kacham dwaro mapamire, joma ok ni gi gimoro kata joma ok tho mar piny kamodo. Ka en yo mar ang'o ma gin nyithindo mar piny onge gi wach maywague, kama en ga'tno'i e simp kata jokacha piny, gi'no, ne ong'ie ne joma ok ni piny chieng'. Nono ne ong'ue eka nywol joma ok ni e achiel mag kar mag jowi, me riwo ndalo mar dhi kanyakla mofuwo mondo ol oyudo wach mabedi mi wi wuondee kod moko makawo jowi."
    }
];